### ISSUE TITLE
I want to check keybinds

### ISSUE THREAD

**Issue by MoltioN1** [1nUrF4c3/ProtoGenesys#1]
Hi, 
So my friend doesnt has insert on his keyboard.
By any chance can you tell me how to change it to another key?
Also what is the aimbot key?

Ty very much for your help

**Comment by 1nUrF4c3** [comment]
change the key used in this line:

https://github.com/1nUrF4c3/ProtoGenesys/blob/8136892d8e63e437f99b3c2ce3fec0c9c5587e79/ProtoGenesys/Core/MainGUI.cpp#L1179
